-- 001_initial.sql: first schema for the host rule store.
--
-- Every rule is identified by a stable `rule_id` (opaque string generated by
-- the caller). The `scope` column holds either the literal string "default"
-- (rules that apply to every registered container) or the opaque session id
-- assigned at RegisterContainer time (rules scoped to one container session).
--
-- `action` and `duration` are stored as canonical lowercase strings rather
-- than enum codes; SQLite is weakly typed so a string column is no more
-- expensive than an integer and keeps rows human-readable under `sqlite3`.
--
-- `ttl_unix_ms` is optional and records when a session- or hold-and-resume
-- rule should self-expire. Rules with no TTL live until the caller removes
-- them.
--
-- `version_token` is a monotonic-per-change opaque string. StreamRules uses
-- it so listeners can de-duplicate an event they already saw in the initial
-- snapshot.

CREATE TABLE IF NOT EXISTS rules (
    rule_id TEXT PRIMARY KEY,
    scope TEXT NOT NULL,
    cedar_source TEXT NOT NULL,
    action TEXT NOT NULL,
    duration TEXT NOT NULL,
    ttl_unix_ms INTEGER,
    version_token TEXT NOT NULL,
    created_at_unix_ms INTEGER NOT NULL,
    updated_at_unix_ms INTEGER NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_rules_scope ON rules (scope);
