//! Contract test between `features/strait/install.sh` and the agent config
//! parser.
//!
//! The devcontainer feature's install script writes a TOML file at
//! `/etc/strait/strait-agent.toml`, and the feature's entrypoint wrapper
//! passes it to every `strait-agent` invocation via `--config`. The agent
//! uses `RawAgentConfig` with `deny_unknown_fields`, which means any
//! schema drift between the install script's heredoc and `AgentConfig`
//! silently breaks the runtime.
//!
//! This test re-creates the TOML the install script would emit (for the
//! default options and for representative custom options) and asserts
//! that `AgentConfig::load` accepts it with the expected field values.
//! It does not shell out to `install.sh` -- the goal is schema pinning,
//! not a second copy of the CI integration test.

use std::path::Path;

use strait_agent::config::AgentConfig;

/// The exact heredoc body from `features/strait/install.sh`, with the
/// four option-provided fields substituted in. Kept as a `format!` so
/// the string here is structurally identical to the shell script and
/// changes to one are easy to mirror in the other.
fn rendered_toml(proxy_port: u16, agent_user: &str, host_socket: &str, policy: &str) -> String {
    format!(
        "# Generated by the strait devcontainer feature at install time.\n\
         # Hand-edits survive restarts but will be overwritten on feature rebuild.\n\
         \n\
         [proxy]\n\
         port = {proxy_port}\n\
         \n\
         [entrypoint]\n\
         agent_user = \"{agent_user}\"\n\
         redirect_ports = [80, 443]\n\
         \n\
         [host]\n\
         socket_path = \"{host_socket}\"\n\
         \n\
         # The Cedar policy path lives here so downstream tooling can discover it\n\
         # without re-reading the feature options. strait-agent picks it up when\n\
         # the proxy subprocess starts.\n\
         #\n\
         # policy_path = \"{policy}\"\n"
    )
}

fn load(toml: &str) -> AgentConfig {
    let dir = tempfile::tempdir().expect("tempdir");
    let path = dir.path().join("strait-agent.toml");
    std::fs::write(&path, toml).expect("write");
    AgentConfig::load(Some(path.as_path())).expect("config should load")
}

#[test]
fn default_options_produce_a_parseable_config() {
    let toml = rendered_toml(
        9443,
        "vscode",
        "/run/strait/host.sock",
        "/etc/strait/policy.cedar",
    );
    let cfg = load(&toml);
    assert_eq!(cfg.proxy_port, 9443);
    assert_eq!(cfg.agent_user.as_deref(), Some("vscode"));
    assert_eq!(cfg.redirect_ports, vec![80, 443]);
    assert_eq!(cfg.host_socket, Path::new("/run/strait/host.sock"));
}

#[test]
fn custom_options_thread_through_to_config() {
    // Matches the second stanza of `.github/workflows/feature-test.yml`:
    // non-default agent_user, proxy_port, and host socket path.
    let toml = rendered_toml(18443, "someoneelse", "/tmp/host.sock", "/tmp/policy.cedar");
    let cfg = load(&toml);
    assert_eq!(cfg.proxy_port, 18443);
    assert_eq!(cfg.agent_user.as_deref(), Some("someoneelse"));
    assert_eq!(cfg.host_socket, Path::new("/tmp/host.sock"));
}

#[test]
fn checked_into_feature_files_match_heredoc_shape() {
    // Guard against accidental drift between this test file and the
    // shell script: if install.sh stops containing the `port = ${PROXY_PORT}`
    // line (or similar), the contract above is meaningless.
    let install = std::fs::read_to_string(
        Path::new(env!("CARGO_MANIFEST_DIR"))
            .parent()
            .expect("agent crate parent")
            .join("features/strait/install.sh"),
    )
    .expect("read install.sh");

    for needle in [
        "[proxy]",
        "port = ${PROXY_PORT}",
        "[entrypoint]",
        "agent_user = \"${AGENT_USER}\"",
        "redirect_ports = [80, 443]",
        "[host]",
        "socket_path = \"${HOST}\"",
    ] {
        assert!(
            install.contains(needle),
            "install.sh missing expected fragment {needle:?}; drift with feature_config_contract.rs"
        );
    }
}
